### ISSUE TITLE
Array lifetime and type

### ISSUE THREAD

**Issue by bluss** [droundy/arrayref#1]
This is some drive by code review as requested :smile:

Issue 1) It looks like the code is not correctly connecting the lifetime of the borrow of the slice with the lifetime that belongs to the reference that comes from the transmute. [Here's a testcase](https://play.rust-lang.org/?gist=ed2a0c4dc0b77bbc6347&version=stable) that shows an aliasing violation.. we can mutate the data while we have a reference to it!

By the way, for pointers, prefer just using casts instead of transmuting. The same caveat with lifetimes still applies though.

The best way to make sure the lifetimes match up is using a function.  For example like [`copy_lifetime`](https://doc.rust-lang.org/src/core/mem.rs.html#454-467), a function you can copy.

Issue 2) Unrestricted transmute. The user's type parameter is trusted, and the user can get bogus results by giving the wrong type.

**Comment by bluss** [comment]
If you don't mind, I think I would write it [like this](https://play.rust-lang.org/?gist=cf7adfc5fcf136f4656b&version=stable). I like the idea behind this code, bounds check and then cast when it's ok. See also [this Q & A](http://stackoverflow.com/questions/29573599/proper-way-to-build-an-array-from-a-slice/29589604) on SO.

**Comment by droundy** [comment]
Thanks so much! I had worried about aliasing, but wasn't clear as to how to do this right.  I've made those changes, and in addition have made the as_array function generic, which seems to allow type inference to decide the type of the array for us.   :)

If you'd care to go for another round of review, I'd be extremely grateful!

**Comment by bluss** [comment]
Looks good to me. I lifted out `$offset`, `$len` outside the unsafe block, but I forgot `$arr`. I guess just having `let slice = &$arr[$offset .. $offset + $len]` outside the unsafe block is the best. That way the user can't slip in unsafe code in the $arr expression by mistake.

**Comment by droundy** [comment]
Thanks for the further suggestion, @bluss ! I hadn't understood why you'd defined a and l before, but now it makes sense.  Even though rust macros are hygienic, that doesn't prevent expressions from containing unsafe code, and putting the "let slice =" outside the unsafe block protects from that.
