### ISSUE TITLE
Soundness issue: Macros should overflow-check integer parameters

### ISSUE THREAD

**Issue by Manishearth** [droundy/arrayref#26]
Found by @veluca93

In the two `_refs` macros, `$pre` and `$post` are added for a bounds check, however there is nothing that checks if they overflow.

https://github.com/droundy/arrayref/blob/6a0d5849e359a9ad29ad096997eba3f1c7ca6b64/src/lib.rs#L112-L113

It's pretty hard to actually trigger this since very-large arrays are not quite allowed by the compiler anyway on at least x86, but it is worth guarding against.

**Comment by droundy** [comment]
I believe I've fixed this, and even made this sum guaranteed to be computed at compile time by changing `let` to `const`.  I'd appreciate a look at my commit if you have time, as it's not the most elegant solution.

**Comment by veluca93** [comment]
Since in Rust no slice can have more than isize::MAX element unless its elements are ZSTs, and the code doesn't do UB with ZSTs, I would say it is fine -- however, I think it would be better to just panic in the overflow case, instead of returning the maximum usize.

Relatedly -- why not `saturating_add` if you were going for saturating semantics?

**Comment by droundy** [comment]
The issue is that I'm not sure how to panic in a const function. I suppose
the answer is to put a not const assert that the min len is less than the
max.
David Roundy

**Comment by veluca93** [comment]
> The issue is that I'm not sure how to panic in a const function. I suppose the answer is to put a not const assert that the min len is less than the max. David Roundy



You can just `panic!`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=220a29c113e540296a43becdce7a4367

**Comment by droundy** [comment]
I switched to saturating add and added an explicit panic afterwards, which seems a reasonable solution.  Somehow after seeing that `checked_add` is not yet `const` it didn't occur to me to look at `saturating_add`.

**Comment by veluca93** [comment]
This should work as far as I can tell!

**Comment by droundy** [comment]
Thanks!
David Roundy
